In [1]:

class Employee:


    # data member to count the number of Employees
    no_of_employees = 0

  #Create a constructor to initialize name, family, salary, department
    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1

  # Create a function to average salary
    @staticmethod
    def average_salary(employees):
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees

 # Create a Fulltime Employee class and it should inherit the properties of Employee class
class FulltimeEmployee(Employee):

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)


def main():
    employees = []
    fte1 = FulltimeEmployee("Employee1", "FamilyName1", 120000, "Management")
    employees.append(fte1)
    fte2 = FulltimeEmployee("Employee2", "FamilyName2", 180000, "RnD")
    employees.append(fte2)
    emp1 = Employee("Employee3", "FamilyName3", 160000, "Marketing")
    employees.append(emp1)
    emp2 = Employee("Employee4", "FamilyName4", 135000, "HR")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
    main()


Average salary: 148750.0


In [2]:
import numpy as np


def replace_maxmium(array, replace_value, axis):
    """ choose from x or y depending on condition: np.where(condition, x, y) """
    output = np.where(array == np.max(
        array, axis=1).reshape(-1, 1), 0 * array, array)
    print(output)


def main():

    # Using NumPy create random vector of size 20 having only float
    # in the range 1-20.

    # continuous uniform distribution in [0, 1).
    # To sample Unif[a, b): (b - a) * random_sample() + a
    random20 = np.random.random_sample(20) * 20 + 1
    print(random20)

    # Reshape the array to 4 by 5
    random20_4by5 = random20.reshape((4, 5))
    print(random20_4by5)

    # Replace the max in each row by 0(axis=1)
    replace_maxmium(random20_4by5, 0, 1)


if __name__ == "__main__":
    main()


[17.30967177 17.18792363 19.10251281  7.85815947  1.67933419  9.711695
  9.75992003  4.64855185  4.26890783 18.01562798 11.39724164 11.71343722
 14.31207805  4.98727364 19.00453181 10.24975912 11.94548433 18.90998172
  9.52307149 18.30924284]
[[17.30967177 17.18792363 19.10251281  7.85815947  1.67933419]
 [ 9.711695    9.75992003  4.64855185  4.26890783 18.01562798]
 [11.39724164 11.71343722 14.31207805  4.98727364 19.00453181]
 [10.24975912 11.94548433 18.90998172  9.52307149 18.30924284]]
[[17.30967177 17.18792363  0.          7.85815947  1.67933419]
 [ 9.711695    9.75992003  4.64855185  4.26890783  0.        ]
 [11.39724164 11.71343722 14.31207805  4.98727364  0.        ]
 [10.24975912 11.94548433  0.          9.52307149 18.30924284]]
